/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rajdeep' at '5/18/18 8:02 PM' with Gradle 2.14.1
 *
 * @author rajdeep, @date 5/18/18 8:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
